apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestDeployment
  labels:
    app: Test_DeploymentPod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Test_DeploymentPod
  template:
    metadata:
      labels:
        app: Test_DeploymentPod
    spec:
      containers:
       —name: Test_DeploymentContainer
          image: 9bc2fc02804d:dev
          ports:
           —containerPort: 80